- Alunos/CamilaPiccinato/Aula 01/Hello.java
> Hello World - Aula 01

- Alunos/LuanGuex/Aula 01/Hello.java
Criação do arquivo Hello.java com System.out.println("Hello, World!") nele.
> Add Hello World - aula 01

- Alunos/Mirielen Goulart/Aula01/Hello.java
> Print Hello World java

- Alunos/Felipe Valdivino Biava/Aula 01/hello.java
> hello word

- Alunos/FelipeHeringer/Aula01/Hello.java
Pull Request Aula 01 do novo Fork
> Commit Aula01

- Alunos/FelipeHeringer/Aula02/Calculadora.java
- Alunos/FelipeHeringer/Aula02/Main.java
- Alunos/FelipeHeringer/Aula02/Menu.java
Adicionado ao novo fork Aula 02 ( Calculadora da Dona Gabrielinha)
> Commit da Aula 02

- Alunos/vinicius cecatto/aula1/Hello.java
- Alunos/vinicius cecatto/aula2/CalculadoraLojaPlantas.java
Regularizado a situação
Removido arquivos adicionais.
> Regularizado situação

- Alunos/leocherini/Aula03/CalcLoja.java
Criação da pasta Aula 03 e adição do Código melhorado.
> Commit aula03

- Alunos/Wellington_Davies/Aula03/CalculadoraAula03.java
Commit da atividade da aula 03
> Entrega do exercício da aula 03

- Alunos/Emanuel Meier/Aula03/CalculadoraLoja.java
Adicionado melhorias solicitadas no código.
> Aprimoramento do código

- Alunos/Emanuel Meier/Aula04/CalculadoraLoja.java
adicionando melhorias no código
> Adicionando aula 04

- Alunos/Bruno Henrique/Aula04/LojaV3.Java
- Alunos/Bruno Henrique/Aula05/Comparativo.md
> Adiciona funcionalidades Aula04 - Explica paradigmas Aula05

- Alunos/Wellington_Davies/Aula04/Calculadora_Aula04.java
- Alunos/Wellington_Davies/Aula05/texto.md
> Entrega da atividade 04

- Alunos/Felipe Gabriel/AULA 01/hello.java
- Alunos/Felipe Gabriel/AULA 02/att2.java
- Alunos/Felipe Gabriel/AULA 03/att3new.java
- Alunos/Felipe Gabriel/AULA 04/Att4.java
- Alunos/Felipe Gabriel/AULA 05/texto.md
- Alunos/Felipe Gabriel/Aula 01/helloworld.java
Enviando novamente atividades 01 até 05 por conta de erro constatado na atividade da aula 05 
(há uma exclusão de um arquivo errado ( Aula 01)
> Enviando as atividades novamente 

- Alunos/Wellington_Davies/Aula06/Cliente.java
- Alunos/Wellington_Davies/Aula06/Loja.java
- Alunos/Wellington_Davies/Aula06/Main.java
- Alunos/Wellington_Davies/Aula06/Vendedor.java
Commit das interações iniciais de classes de objetos
> Commit da aula 06

- Alunos/Bruno Henrique/Aula06/Cliente.java
- Alunos/Bruno Henrique/Aula06/Loja.java
- Alunos/Bruno Henrique/Aula06/Main.java
- Alunos/Bruno Henrique/Aula06/Vendedor.java
> Implementa OOP MyPlant

- Alunos/Emanuel Meier/Aula06/Calculadora.java
- Alunos/Emanuel Meier/Aula06/Cliente.java
- Alunos/Emanuel Meier/Aula06/Loja.java
- Alunos/Emanuel Meier/Aula06/Vendedor.java
> Adicionando atividade da aula 6

- Alunos/Kallyan Mombach/Aula06/Cliente.java
- Alunos/Kallyan Mombach/Aula06/Loja.java
- Alunos/Kallyan Mombach/Aula06/Main.java
- Alunos/Kallyan Mombach/Aula06/Vendedor.java
utilizando as Classes na calculadora da Dona Gabrielinha
> Aula 06 Classes

- Alunos/Wellington_Davies/Aula07/Gerente.java
- Alunos/Wellington_Davies/Aula07/Main.java
- Alunos/Wellington_Davies/Aula07/ProcessaPedido.java
- Alunos/Wellington_Davies/Aula07/Superclasses/Cliente.java
- Alunos/Wellington_Davies/Aula07/Superclasses/Endereco.java
- Alunos/Wellington_Davies/Aula07/Superclasses/Funcionario.java
- Alunos/Wellington_Davies/Aula07/Superclasses/Item.java
- Alunos/Wellington_Davies/Aula07/Superclasses/Pedido.java
- Alunos/Wellington_Davies/Aula07/Vendedor.java
Superclasses e subclasses junto ao Main, com menu.
> Commit do exercício da aula 07

- Alunos/Emanuel Meier/Aula07/Cliente.java
- Alunos/Emanuel Meier/Aula07/Endereco.java
- Alunos/Emanuel Meier/Aula07/Funcionario.java
- Alunos/Emanuel Meier/Aula07/Gerente.java
- Alunos/Emanuel Meier/Aula07/Item.java
- Alunos/Emanuel Meier/Aula07/Main.java
- Alunos/Emanuel Meier/Aula07/Pedido.java
- Alunos/Emanuel Meier/Aula07/Pessoa.java
- Alunos/Emanuel Meier/Aula07/ProcessaPedido.java
- Alunos/Emanuel Meier/Aula07/Vendedor.java
Adicionado novas melhorias na calculadora.
> Adicionando arquivos da aula 7

- Alunos/Kallyan Mombach/Aula07/Cliente.java
- Alunos/Kallyan Mombach/Aula07/Endereco.java
- Alunos/Kallyan Mombach/Aula07/Gerente.java
- Alunos/Kallyan Mombach/Aula07/Item.java
- Alunos/Kallyan Mombach/Aula07/Loja.java
- Alunos/Kallyan Mombach/Aula07/Main.java
- Alunos/Kallyan Mombach/Aula07/Pedido.java
- Alunos/Kallyan Mombach/Aula07/ProcessaPedido.java
- Alunos/Kallyan Mombach/Aula07/Vendedor.java
Adicionando Classes e herança na calculadora da Gabrielinha.
> Adicionando Classes na Calculadora

- Alunos/Bruno Henrique/Aula07/Principal/Cliente.java
- Alunos/Bruno Henrique/Aula07/Principal/Endereco.java
- Alunos/Bruno Henrique/Aula07/Principal/Item.java
- Alunos/Bruno Henrique/Aula07/Principal/Loja.java
- Alunos/Bruno Henrique/Aula07/Principal/Main.java
- Alunos/Bruno Henrique/Aula07/Principal/Pedido.java
- Alunos/Bruno Henrique/Aula07/Principal/ProcessaPedido.java
- Alunos/Bruno Henrique/Aula07/Subclasses/Gerente.java
- Alunos/Bruno Henrique/Aula07/Subclasses/Vendedor.java
- Alunos/Bruno Henrique/Aula07/Superclasses/Funcionario.java
> Commit Aula07

- Alunos/Jhonatan Lucas Chiari/Aula_07/Cliente.java
- Alunos/Jhonatan Lucas Chiari/Aula_07/Endereco.java
- Alunos/Jhonatan Lucas Chiari/Aula_07/Gerente.java
- Alunos/Jhonatan Lucas Chiari/Aula_07/Item.java
- Alunos/Jhonatan Lucas Chiari/Aula_07/Loja.java
- Alunos/Jhonatan Lucas Chiari/Aula_07/Main.java
- Alunos/Jhonatan Lucas Chiari/Aula_07/Pedido.java
- Alunos/Jhonatan Lucas Chiari/Aula_07/Pessoa.java
- Alunos/Jhonatan Lucas Chiari/Aula_07/ProcessaPedido.java
- Alunos/Jhonatan Lucas Chiari/Aula_07/Vendedor.java
Entrega da atividade da Aula 07 - Herança e Polimorfismo
> Update Aula 07

- Alunos/Eduardo de Oliveira Bertolin/Aula 07/CalculadoraPlantas.java
- Alunos/Eduardo de Oliveira Bertolin/Aula 07/Cliente.java
- Alunos/Eduardo de Oliveira Bertolin/Aula 07/Endereco.java
- Alunos/Eduardo de Oliveira Bertolin/Aula 07/Gerente.java
- Alunos/Eduardo de Oliveira Bertolin/Aula 07/Item.java
- Alunos/Eduardo de Oliveira Bertolin/Aula 07/Loja.java
- Alunos/Eduardo de Oliveira Bertolin/Aula 07/Pedido.java
- Alunos/Eduardo de Oliveira Bertolin/Aula 07/Pessoa.java
- Alunos/Eduardo de Oliveira Bertolin/Aula 07/ProcessaPedido.java
- Alunos/Eduardo de Oliveira Bertolin/Aula 07/TesteProcessaPedido.java
- Alunos/Eduardo de Oliveira Bertolin/Aula 07/Vendedor.java
Separado classes em arquivos diferentes
adicionado os métodos requeridos na aula 07
> Adicionando arquivos aula 07

- Alunos/Bruno Henrique/Revisao prova/Carro.java
- Alunos/Bruno Henrique/Revisao prova/Clientes.java
- Alunos/Bruno Henrique/Revisao prova/Main.java
- Alunos/Bruno Henrique/Revisao prova/Moto.java
- Alunos/Bruno Henrique/Revisao prova/Veiculo.java
> Revisão prova

- Alunos/Bruno Henrique/Prova_1Tri/Cliente.java
- Alunos/Bruno Henrique/Prova_1Tri/Main.java
- Alunos/Bruno Henrique/Prova_1Tri/Quarto.java
- Alunos/Bruno Henrique/Prova_1Tri/QuartoDuplo.java
- Alunos/Bruno Henrique/Prova_1Tri/QuartoSimples.java
> Prova_1tri

- Alunos/Jhonatan Lucas Chiari/Prova_1trim/Cliente.java
- Alunos/Jhonatan Lucas Chiari/Prova_1trim/Hotel.java
- Alunos/Jhonatan Lucas Chiari/Prova_1trim/Main.java
- Alunos/Jhonatan Lucas Chiari/Prova_1trim/Quarto.java
- Alunos/Jhonatan Lucas Chiari/Prova_1trim/QuartoDuplo.java
- Alunos/Jhonatan Lucas Chiari/Prova_1trim/QuartoSimples.java
- Alunos/Jhonatan Lucas Chiari/Prova_1trim/Reserva.java
Entrega da resolução da prova de primeiro bimestre.
> Upload Prova_1tri

- Alunos/Wellington_Davies/Prova_1tri/Clientes.java
- Alunos/Wellington_Davies/Prova_1tri/Hotel.java
- Alunos/Wellington_Davies/Prova_1tri/HotelMain.java
- Alunos/Wellington_Davies/Prova_1tri/Quarto.java
- Alunos/Wellington_Davies/Prova_1tri/QuartoDuplo.java
- Alunos/Wellington_Davies/Prova_1tri/QuartoSimples.java
- Alunos/Wellington_Davies/Prova_1tri/Reserva.java
Entrega da prova do 1 bimestre...
> Entrega da prova

- Alunos/Kallyan Mombach/PROVA_1TRI/Cliente.java
- Alunos/Kallyan Mombach/PROVA_1TRI/Hotel.java
- Alunos/Kallyan Mombach/PROVA_1TRI/Main.java
- Alunos/Kallyan Mombach/PROVA_1TRI/Quarto.java
- Alunos/Kallyan Mombach/PROVA_1TRI/QuartoDuplo.java
- Alunos/Kallyan Mombach/PROVA_1TRI/QuartoSimples.java
- Alunos/Kallyan Mombach/PROVA_1TRI/Reserva.java
> PROVA HOTEL

- Alunos/Emanuel Meier/Prova_1Tri/Cliente.java
- Alunos/Emanuel Meier/Prova_1Tri/Main.java
- Alunos/Emanuel Meier/Prova_1Tri/Quarto.java
- Alunos/Emanuel Meier/Prova_1Tri/QuartoDuplo.java
- Alunos/Emanuel Meier/Prova_1Tri/QuartoSimples.java
- Alunos/Emanuel Meier/Prova_1Tri/Reserva.java
Arquivos da prova adicionados.
> Adicionando arquivos da prova.

- Alunos/MatheusFelipePimenta/Prova_1trim/Cliente.java
- Alunos/MatheusFelipePimenta/Prova_1trim/HotelSistema.java
- Alunos/MatheusFelipePimenta/Prova_1trim/Quarto.java
- Alunos/MatheusFelipePimenta/Prova_1trim/QuartoDuplo.java
- Alunos/MatheusFelipePimenta/Prova_1trim/QuartoSimples.java
- Alunos/MatheusFelipePimenta/Prova_1trim/Reserva.java
> Prova - Hotel

- Alunos/Julia-Soares/Aula09/Calculadora.java
- Alunos/Julia-Soares/Aula09/EntradaInvalida.java
> Entrega da atividade 09

- Alunos/Wellington_Davies/Aula11/Main.java
Entrega da atividade da aula 11
> Atividade Aula11

- Alunos/Kallyan Mombach/Aula11/Main.java
> Atividade Aula 11

- Alunos/Emanuel Meier/Aula11/Main.java
Lista de exercícios StreamAPI.
> Adicionando lista de exercícios StreamAPI

- Alunos/Jhonatan Lucas Chiari/Aula_11/Main.java
Entrega da Lista de exercícios StreamAPI
> Update Aula 11

- Alunos/Kaua-ferreira/Aula12/CurrentConditions.java
- Alunos/Kaua-ferreira/Aula12/Day.java
- Alunos/Kaua-ferreira/Aula12/VisualCrossingService.java
- Alunos/Kaua-ferreira/Aula12/WeatherData.java
- Alunos/Kaua-ferreira/Aula12/main.java
- Alunos/Kaua-ferreira/Prova_2tri/Country.java
- Alunos/Kaua-ferreira/Prova_2tri/JsonDataManager.java
- Alunos/Kaua-ferreira/Prova_2tri/Main.java
- Alunos/Kaua-ferreira/Prova_2tri/Network.java
- Alunos/Kaua-ferreira/Prova_2tri/Rating.java
- Alunos/Kaua-ferreira/Prova_2tri/Serie.java
- Alunos/Kaua-ferreira/Prova_2tri/TVMazeService.java
- Alunos/Kaua-ferreira/Prova_2tri/Usuario.java
Esta sendo enviado os códigos da prova e da aula 12
> Entrega da Prova_2tri e Aula12

- Alunos/Kallyan Mombach/Aula12/ClasseTempo.java
- Alunos/Kallyan Mombach/Aula12/MainTempo.java
- Alunos/Kallyan Mombach/Aula12/TempoEstrutura.java
- Alunos/Kallyan Mombach/PROVA_2TRI/ApiConnector.java
- Alunos/Kallyan Mombach/PROVA_2TRI/Json.java
- Alunos/Kallyan Mombach/PROVA_2TRI/Main.java
- Alunos/Kallyan Mombach/PROVA_2TRI/Perfil.java
- Alunos/Kallyan Mombach/PROVA_2TRI/Serie.java
- Alunos/Kallyan Mombach/PROVA_2TRI/SerieEstrutura.java
Adicionando arquivos da avaliação segundo trimestre
> PROVA SEGUNDO TRIMESTRE

- Alunos/Bruno Henrique/Aula12/App.java
- Alunos/Bruno Henrique/Aula12/CurrentConditions.java
- Alunos/Bruno Henrique/Aula12/DailyWeather.java
- Alunos/Bruno Henrique/Aula12/HttpService.java
- Alunos/Bruno Henrique/Aula12/Main.java
- Alunos/Bruno Henrique/Aula12/UrlBuilder.java
- Alunos/Bruno Henrique/Aula12/WeatherApiService.java
- Alunos/Bruno Henrique/Aula12/WeatherResponse.java
- Alunos/Bruno Henrique/Prova_2tri/App.java
- Alunos/Bruno Henrique/Prova_2tri/HttpService.java
- Alunos/Bruno Henrique/Prova_2tri/JsonParserService.java
- Alunos/Bruno Henrique/Prova_2tri/ListaDeSeries.java
- Alunos/Bruno Henrique/Prova_2tri/LocalDateAdapter.java
- Alunos/Bruno Henrique/Prova_2tri/Main.java
- Alunos/Bruno Henrique/Prova_2tri/Serie.java
- Alunos/Bruno Henrique/Prova_2tri/UrlBuilder.java
Envio definitivo do projeto "Atividade Avaliativa - Minhas séries de TV"
> Prova_2tri
